language: php

notifications:
  email: false

php:
  - '5.6'
  - '7.0'
  - '7.1'

mysql:
  database: tuner
  username: root
  encoding: utf8

before_install:
  - mysql -u root -e "CREATE DATABASE tuner COLLATE 'utf8_general_ci';"
  - mysql -u root tuner < tuner.sql
  - composer install

script: phpunit
